{% set name = "sphinxcontrib-programoutput" %}
{% set version = "0.17" %}
{% set sha256 = "300ee9b8caee8355d25cc74b4d1c7efd12e608d2ad165e3141d31e6fbc152b7f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python >=3.6
    - setuptools
    - sphinx

  run:
    - python >=3.6
    - sphinx

test:
  imports:
    - sphinxcontrib.programoutput

about:
  home: https://bitbucket.org/birkenfeld/sphinx-contrib
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE
  summary: Sphinx extension to include program output

  description: |
    A Sphinx extension to literally insert the output of arbitrary commands
    into documents, helping you to keep your command examples up to date.
  doc_url: https://sphinxcontrib-programoutput.readthedocs.org/
  dev_url: https://bitbucket.org/birkenfeld/sphinx-contrib

extra:
  recipe-maintainers:
    - holgern
    - anjos
