travis:
  secure:
    BINSTAR_TOKEN: rPelNNQAhpTiwfn0yxxGV31ipnyzvPZN4Rx7kYlKJY+p8pAmeIJEljgH40U3RlLkW5d1OKWUEzivw2d7P0tw8I3wk7hNJKjkLN3ekz0dFhMi5JJOYEt+yz/XvXLkZDUh6tO7RED3Du++CczivhodvTpRiz2pwMOxz9r0me0K4IOxqkjIx6H831AMELzVHHjuBZTrjb2+LWRNr/tfa8r67QE0otypbCo1aw00jfKMP2TzWzo/S7H10zWBdg66SllSuJ7KJNye4QWPWVpBtH6vMKSc5uV2oGEq80Qeum501cHleYJWpaTLQLQuLoJ2xl6v9r+FtHy/bCExDBePr/ZSxboO2f4MuawcXkNvq3wz9xPsvJzRM5zXPj5GUguMMtlm0EHwIduuIVFRIdD3csF7vr98QqAP4+VKIQjPtpFSlgtmQrzxZHhJGTF7SPTq+Dx6sEQgSMc2tHQpt4DJR9HjBxRjgpqwb2KzGlkrLS9gpQPWbafST8n4fjdZIjk4L1Ts9YAhdko1245ZCWuxZEE5Fdc9dBFxwyq7t3NcTj3feAnnhvraNVkw3gruFxU5AXPYTgktzf0L3yx5fo8jysEyybgKwCp9/dH9feJRGmI0XukMm9Cn97hRZeKD4e/TmUVJOxKQ3sUVW8OI7pOpqM+7hFbeFaX6tpFZpxifIV6GhS0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
