travis:
  secure:
    BINSTAR_TOKEN: pOMtUp70RydX1qCPBcgi5Ejbh5R7WRxr615X+kwQCKOAaBkvXmQxZB8zU64xP6J6TBE/g+TbiaL3MDiTOKZhE3WpC5BWOEnWQ4FOm0gb307otZLPHFSKf6Pbiw3zMcRHv/f8ZJQMCmHCzlO36FHM9v+B5RM4ZKz2KhRBwv5p5oJTcx2pz8faVJWZyYUvzPv2Yx7bGa/eyR2uVd0NwCJ/zJXBf/wqVeCMeAisqrWiVZRoOoe/1iBLuHBMhLkK0JGBezLBhUTgLF2nfObQPHqanwJZnGcIbkFKldFCyVqECaxma47ViatU9qoI1oHYX9mR4OK7Gi4qQ1vx5Se2iOqLKuZXS4goVsC2eNR2KwfCVPEgG5KAhXic1OILnF0ji+jcOGYnTrYmVzNKzx0vzwoA+MISZ4/5d5ljnqZpe2QPacnx3TjEzkI17jmdbPXgPx1CzZLD5KHGzdvD9iHitgoRdpkIsrbxJQlMPXddOk34Te7HHQxVl+re/bV+1qg/SnJRdoQs6L2V3nPunk3G0HeAAsJUl9fBpFI1TNiUzFE/G6+Aq4F2NYuoZxZsjNZv3JwEhiQXsRqloTULDtwMgH0HZWuAtb6/sYhhdeCVO12MrPbhLbRs+5pK6wqYtwBYBiGAeYIZkKwd4nOCh9iukX9oyceqB1Lqdp8jxjORVeVHX88=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
